import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/common/Header";
import Footer from "@/Components/common/Footer";
import { UserProvider } from "@/Components/context/userContext";
 

 

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <UserProvider>
           
          {children}
        </UserProvider>
        
        
        </body>
    </html>
  );
}
